### ISSUE TITLE
mcbarint = 100 and echoing command

### ISSUE THREAD

**Issue by pgbarletta** [drroe/AmberMdPrep#1]
First of all, thank you for your paper and this script. I see myself using your work for a long time.

I'd like to suggest 2 minor changes:

1. I noticed you write all options into the input files, even those that default to the desired values. Only one missing is `mcbarint = 100`.
2. Besides printing the running step (eg: `minimization: step5`), echoing the exact command being ran would be a nice add. Useful for debugging and restarting runs.

**Comment by drroe** [comment]
Sorry for the delay - I have to get in the habit of checking this more regularly! These are good suggestions - hopefully I will find time to update soon.

**Comment by drroe** [comment]
@pgbarletta This should now be addressed. `mcbarint` is now a keyword. Let me know if it works for you. Sorry it took so long.

Regarding the second issue, you can do a test run with the `--test` flag that will echo the commands to be used. Does that work for you?

**Comment by pgbarletta** [comment]
Yes! You're right, that should do it. 
While I was trying the `--test` flag, I ran into a minor `--skipfinaleq` bug. The fix was rather easy, so I went ahead and made a PR, I hope that's ok.

**Comment by drroe** [comment]
Since this seems resolved, I'll close it for now. Please open it back up if it hasn't been properly addressed.
